-- AlterTable
ALTER TABLE "NutritionTarget" ADD COLUMN     "carbs" INTEGER NOT NULL DEFAULT 250,
ADD COLUMN     "fats" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN     "protein" INTEGER NOT NULL DEFAULT 150;
